BEGIN;
CREATE TABLE `Alert` (`AlertID` integer NOT NULL PRIMARY KEY, `Decision` varchar(50) NOT NULL);
CREATE TABLE `AlertReplica` (`ReplicaID` integer NOT NULL PRIMARY KEY, `ReplicaNumber` integer NOT NULL, `ChannelID` integer NOT NULL, `ChannelProbability` double precision NOT NULL, `AlertID` integer NOT NULL);
CREATE TABLE `AstroObject` (`AstroObjectID` integer NOT NULL PRIMARY KEY, `Catalog` varchar(500) NOT NULL, `IDinCatalog` integer NOT NULL, `IsPointSource` bool NOT NULL);
CREATE TABLE `Attribute` (`AttrName` varchar(100) NOT NULL PRIMARY KEY, `IsScaled` bool NOT NULL, `DataType` varchar(500) NOT NULL);
CREATE TABLE `AttributeValue` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `ContainerID` integer NOT NULL, `ContainerType` varchar(1) NOT NULL, `ComputedAt` datetime NOT NULL, `Value` double precision NOT NULL, `Annotation` varchar(500) NOT NULL, `Confidence` double precision NOT NULL, `AttrName` varchar(100) NOT NULL);
CREATE TABLE `Locus` (`LocusID` integer NOT NULL PRIMARY KEY, `RA` double precision NOT NULL, `Decl` double precision NOT NULL);
ALTER TABLE `AttributeValue` ADD CONSTRAINT `AttributeValue_AttrName_82b182ad6ec4bf0_uniq` UNIQUE (`AttrName`, `ContainerID`, `ContainerType`, `ComputedAt`);
ALTER TABLE `AstroObject` ADD COLUMN `LocusID` integer NOT NULL;
ALTER TABLE `AstroObject` ALTER COLUMN `LocusID` DROP DEFAULT;
ALTER TABLE `AlertReplica` ADD COLUMN `AstroObjectID` integer NOT NULL;
ALTER TABLE `AlertReplica` ALTER COLUMN `AstroObjectID` DROP DEFAULT;
ALTER TABLE `AlertReplica` ADD COLUMN `LocusID` integer NOT NULL;
ALTER TABLE `AlertReplica` ALTER COLUMN `LocusID` DROP DEFAULT;
ALTER TABLE `Alert` ADD COLUMN `LocusID` integer NOT NULL;
ALTER TABLE `Alert` ALTER COLUMN `LocusID` DROP DEFAULT;
ALTER TABLE `AlertReplica` ADD CONSTRAINT `AlertReplica_AlertID_1b165d11ad19dd51_fk_Alert_AlertID` FOREIGN KEY (`AlertID`) REFERENCES `Alert` (`AlertID`);
CREATE INDEX `AlertReplica_cd0a6016` ON `AlertReplica` (`AlertID`);
ALTER TABLE `AttributeValue` ADD CONSTRAINT `AttributeValue_AttrName_3256e603734db135_fk_Attribute_AttrName` FOREIGN KEY (`AttrName`) REFERENCES `Attribute` (`AttrName`);
CREATE INDEX `AttributeValue_931c9a6a` ON `AttributeValue` (`AttrName`);
CREATE INDEX `AstroObject_77cb0242` ON `AstroObject` (`LocusID`);
ALTER TABLE `AstroObject` ADD CONSTRAINT `AstroObject_LocusID_43ef91faea7159ef_fk_Locus_LocusID` FOREIGN KEY (`LocusID`) REFERENCES `Locus` (`LocusID`);
CREATE INDEX `AlertReplica_fdd05c7d` ON `AlertReplica` (`AstroObjectID`);
ALTER TABLE `AlertReplica` ADD CONSTRAINT `Aler_AstroObjectID_4764defa970e1456_fk_AstroObject_AstroObjectID` FOREIGN KEY (`AstroObjectID`) REFERENCES `AstroObject` (`AstroObjectID`);
CREATE INDEX `AlertReplica_77cb0242` ON `AlertReplica` (`LocusID`);
ALTER TABLE `AlertReplica` ADD CONSTRAINT `AlertReplica_LocusID_7a74441cd1442793_fk_Locus_LocusID` FOREIGN KEY (`LocusID`) REFERENCES `Locus` (`LocusID`);
CREATE INDEX `Alert_77cb0242` ON `Alert` (`LocusID`);
ALTER TABLE `Alert` ADD CONSTRAINT `Alert_LocusID_3394d64f85120c41_fk_Locus_LocusID` FOREIGN KEY (`LocusID`) REFERENCES `Locus` (`LocusID`);

COMMIT;
