BEGIN;
CREATE TABLE `LADB_alert` (`AlertID` integer NOT NULL PRIMARY KEY, `Decision` varchar(50) NOT NULL);
CREATE TABLE `LADB_alertreplica` (`ReplicaID` integer NOT NULL PRIMARY KEY, `ReplicaNumber` integer NOT NULL, `ChannelID` integer NOT NULL, `ChannelProbability` double precision NOT NULL, `AlertID_id` integer NOT NULL);
CREATE TABLE `LADB_astroobject` (`AstroObjectID` integer NOT NULL PRIMARY KEY, `Catalog` varchar(500) NOT NULL, `IDinCatalog` integer NOT NULL, `IsPointSource` bool NOT NULL);
CREATE TABLE `LADB_attribute` (`AttrName` varchar(100) NOT NULL PRIMARY KEY, `IsScaled` bool NOT NULL, `DataType` varchar(500) NOT NULL);
CREATE TABLE `LADB_attributevalue` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `ContainerID` integer NOT NULL, `ContainerType` varchar(1) NOT NULL, `ComputedAt` datetime NOT NULL, `Value` double precision NOT NULL, `Annotation` varchar(500) NOT NULL, `Confidence` double precision NOT NULL, `AttrName_id` varchar(100) NOT NULL);
CREATE TABLE `LADB_locus` (`LocusID` integer NOT NULL PRIMARY KEY, `RA` double precision NOT NULL, `Decl` double precision NOT NULL);
ALTER TABLE `LADB_attributevalue` ADD CONSTRAINT `LADB_attributevalue_AttrName_id_655bd5c81550e192_uniq` UNIQUE (`AttrName_id`, `ContainerID`, `ContainerType`, `ComputedAt`);
ALTER TABLE `LADB_astroobject` ADD COLUMN `LocusID_id` integer NOT NULL;
ALTER TABLE `LADB_astroobject` ALTER COLUMN `LocusID_id` DROP DEFAULT;
ALTER TABLE `LADB_alertreplica` ADD COLUMN `AstroObjectID_id` integer NOT NULL;
ALTER TABLE `LADB_alertreplica` ALTER COLUMN `AstroObjectID_id` DROP DEFAULT;
ALTER TABLE `LADB_alertreplica` ADD COLUMN `LocusID_id` integer NOT NULL;
ALTER TABLE `LADB_alertreplica` ALTER COLUMN `LocusID_id` DROP DEFAULT;
ALTER TABLE `LADB_alert` ADD COLUMN `LocusID_id` integer NOT NULL;
ALTER TABLE `LADB_alert` ALTER COLUMN `LocusID_id` DROP DEFAULT;
ALTER TABLE `LADB_alertreplica` ADD CONSTRAINT `LADB_alertrepl_AlertID_id_7ad58f23197dd5fd_fk_LADB_alert_AlertID` FOREIGN KEY (`AlertID_id`) REFERENCES `LADB_alert` (`AlertID`);
CREATE INDEX `LADB_alertreplica_fb85bbed` ON `LADB_alertreplica` (`AlertID_id`);
ALTER TABLE `LADB_attributevalue` ADD CONSTRAINT `LADB_att_AttrName_id_7a6dd9330a44beed_fk_LADB_attribute_AttrName` FOREIGN KEY (`AttrName_id`) REFERENCES `LADB_attribute` (`AttrName`);
CREATE INDEX `LADB_attributevalue_abdad757` ON `LADB_attributevalue` (`AttrName_id`);
CREATE INDEX `LADB_astroobject_81cd4d51` ON `LADB_astroobject` (`LocusID_id`);
ALTER TABLE `LADB_astroobject` ADD CONSTRAINT `LADB_astroobje_LocusID_id_25f7445ba1bd3c8b_fk_LADB_locus_LocusID` FOREIGN KEY (`LocusID_id`) REFERENCES `LADB_locus` (`LocusID`);
CREATE INDEX `LADB_alertreplica_5585987a` ON `LADB_alertreplica` (`AstroObjectID_id`);
ALTER TABLE `LADB_alertreplica` ADD CONSTRAINT `D11dbb1f3a4646be4cd050140c01b444` FOREIGN KEY (`AstroObjectID_id`) REFERENCES `LADB_astroobject` (`AstroObjectID`);
CREATE INDEX `LADB_alertreplica_81cd4d51` ON `LADB_alertreplica` (`LocusID_id`);
ALTER TABLE `LADB_alertreplica` ADD CONSTRAINT `LADB_alertrepl_LocusID_id_1564f948c1a33c58_fk_LADB_locus_LocusID` FOREIGN KEY (`LocusID_id`) REFERENCES `LADB_locus` (`LocusID`);
CREATE INDEX `LADB_alert_81cd4d51` ON `LADB_alert` (`LocusID_id`);
ALTER TABLE `LADB_alert` ADD CONSTRAINT `LADB_alert_LocusID_id_6b18a14df7d0623c_fk_LADB_locus_LocusID` FOREIGN KEY (`LocusID_id`) REFERENCES `LADB_locus` (`LocusID`);

COMMIT;
